import streamlit as st
import random
st.set_page_config(page_title="California ECE Practice", page_icon="🌴", layout="wide")
QUESTIONS=[{'domain': 'Approaches to Learning',
  'question': 'A child tries several ways to finish a puzzle before asking for help.',
  'options': ['Persistence', 'Memorization', 'Avoidance', 'Compliance only'],
  'answer': 0,
  'explanation': 'Persistence is a key approach-to-learning behavior.'},
 {'domain': 'Approaches to Learning',
  'question': 'A child independently chooses materials and begins a project.',
  'options': ['Initiative', 'Dependence', 'Punishment avoidance', 'Passive observation'],
  'answer': 0,
  'explanation': 'Independent engagement shows initiative.'},
 {'domain': 'Approaches to Learning',
  'question': 'A child becomes distracted during a small-group activity. Best support?',
  'options': ['Use a brief prompt to help the child re-engage', 'Publicly criticize the child', 'Remove all choices', 'End the activity'],
  'answer': 0,
  'explanation': 'Supportive prompting builds attention without shaming.'},
 {'domain': 'Approaches to Learning',
  'question': 'When an activity becomes difficult, the best response is to:',
  'options': ['Encourage effort and offer appropriate support',
              'Complete it for the child',
              'Tell the child to quit',
              'Compare the child with peers'],
  'answer': 0,
  'explanation': 'Persistence grows when adults support effort and problem-solving.'},
 {'domain': 'Approaches to Learning',
  'question': 'Which feedback best supports learning?',
  'options': ['You kept trying even when that was hard.', "You're the smartest.", 'You never make mistakes.', 'Only fast answers matter.'],
  'answer': 0,
  'explanation': 'Process-focused feedback supports persistence.'},
 {'domain': 'Social & Emotional Development',
  'question': 'Two children want the same truck. Best adult response?',
  'options': ['Coach them to express needs and work out turns',
              'Take it away all day',
              'Choose a favorite child',
              'Tell them feelings do not matter'],
  'answer': 0,
  'explanation': 'Coaching supports social problem-solving.'},
 {'domain': 'Social & Emotional Development',
  'question': "A child says, 'I'm mad because he knocked down my blocks.' This shows:",
  'options': ['Emotional awareness', 'Counting', 'Letter knowledge', 'Gross motor skill'],
  'answer': 0,
  'explanation': 'Naming a feeling and its cause shows emotional awareness.'},
 {'domain': 'Social & Emotional Development',
  'question': 'Which question best supports empathy?',
  'options': ['How do you think your friend felt?', 'Who is the fastest?', 'What color is that?', 'Can you copy this?'],
  'answer': 0,
  'explanation': 'Perspective-taking supports empathy.'},
 {'domain': 'Social & Emotional Development',
  'question': 'A shy child watches a group before joining. Best support?',
  'options': ['Offer a low-pressure way to enter play',
              'Force immediate participation',
              'Label the child antisocial',
              'Send the child away'],
  'answer': 0,
  'explanation': 'Gentle entry respects temperament and encourages participation.'},
 {'domain': 'Social & Emotional Development',
  'question': 'A child is frustrated by a drawing. Best response?',
  'options': ['Acknowledge the feeling and encourage another attempt',
              'Throw the drawing away',
              'Say frustration is silly',
              "Compare with another child's work"],
  'answer': 0,
  'explanation': 'Emotion coaching supports regulation.'},
 {'domain': 'Language, Literacy & English Language Development',
  'question': 'Which activity best supports phonological awareness?',
  'options': ["Clapping syllables in children's names", 'Copying paragraphs', 'Tracing shapes only', 'Counting blocks'],
  'answer': 0,
  'explanation': 'Sound play supports phonological awareness.'},
 {'domain': 'Language, Literacy & English Language Development',
  'question': "While reading, an adult asks, 'What do you think will happen next?' This supports:",
  'options': ['Comprehension and oral language', 'Gross motor strength', 'Self-feeding', 'Color recognition only'],
  'answer': 0,
  'explanation': 'Prediction supports comprehension and language.'},
 {'domain': 'Language, Literacy & English Language Development',
  'question': 'A child makes letter-like marks for a pretend grocery list. This is:',
  'options': ['Emergent writing', 'Formal algebra', 'Gross motor development', 'Scientific measurement'],
  'answer': 0,
  'explanation': 'Early writing attempts are part of emergent writing.'},
 {'domain': 'Language, Literacy & English Language Development',
  'question': 'A multilingual child uses a home-language word during play. Best response?',
  'options': ['Value the communication and connect it to English naturally',
              'Ban the home language',
              'Ignore the child',
              'Correct harshly'],
  'answer': 0,
  'explanation': 'Home language is an asset for communication and learning.'},
 {'domain': 'Language, Literacy & English Language Development',
  'question': 'Which strategy best supports a child learning English?',
  'options': ['Use visuals, gestures, routines, and meaningful conversation',
              'Demand perfect grammar first',
              'Avoid peer interaction',
              'Stop home-language use'],
  'answer': 0,
  'explanation': 'Multiple supports make language accessible.'},
 {'domain': 'Language, Literacy & English Language Development',
  'question': "An adult expands 'Dog run' to 'Yes, the brown dog is running fast.' This supports:",
  'options': ['Language expansion', 'Punishment', 'Number sense', 'Motor planning'],
  'answer': 0,
  'explanation': 'Expansion models richer vocabulary and grammar.'},
 {'domain': 'Mathematics',
  'question': "A child counts five blocks and says 'five' for the total. This demonstrates:",
  'options': ['Cardinality', 'Rhyming', 'Empathy', 'Balance'],
  'answer': 0,
  'explanation': 'The last number counted tells how many are in the set.'},
 {'domain': 'Mathematics',
  'question': 'Which activity best supports classification?',
  'options': ['Sorting buttons by shape or size', 'Running outside', 'Reciting a poem', 'Painting freely'],
  'answer': 0,
  'explanation': 'Classification groups objects by shared attributes.'},
 {'domain': 'Mathematics',
  'question': 'A child continues red-blue-red-blue with another red block. This shows:',
  'options': ['Patterning', 'Self-help', 'Narrative skill', 'Phonological awareness'],
  'answer': 0,
  'explanation': 'The child recognizes and extends a repeating pattern.'},
 {'domain': 'Mathematics',
  'question': 'Children compare two towers to see which is taller. This supports:',
  'options': ['Measurement concepts', 'Rhyming', 'Emotional labeling', 'Print awareness'],
  'answer': 0,
  'explanation': 'Comparing height is early measurement.'},
 {'domain': 'Mathematics',
  'question': 'Which is most developmentally appropriate for early math?',
  'options': ['Hands-on counting with real objects',
              'Timed multiplication tests',
              'Abstract algebra worksheets',
              'Long written calculation drills'],
  'answer': 0,
  'explanation': 'Concrete experiences support early mathematical understanding.'},
 {'domain': 'Science',
  'question': 'Children place ice in sun and shade and observe what happens. This supports:',
  'options': ['Observation and comparison', 'Rhyming', 'Letter formation', 'Turn-taking only'],
  'answer': 0,
  'explanation': 'Children compare change under different conditions.'},
 {'domain': 'Science',
  'question': 'Which question best encourages scientific thinking?',
  'options': ['What do you notice about these two leaves?',
              'What answer did I tell you?',
              'Can you copy this sentence?',
              'Who finished first?'],
  'answer': 0,
  'explanation': 'Open observation questions support inquiry.'},
 {'domain': 'Science',
  'question': 'A child predicts which objects will sink before testing them. This demonstrates:',
  'options': ['Prediction and investigation', 'Phonics', 'Dance', 'Self-care'],
  'answer': 0,
  'explanation': 'Prediction followed by testing is scientific inquiry.'},
 {'domain': 'Science',
  'question': "When a child's prediction is incorrect, the adult should:",
  'options': ['Treat the result as useful evidence and discuss it', 'Say the child failed', 'End the experiment', 'Change the result'],
  'answer': 0,
  'explanation': 'Science learning grows from comparing predictions with evidence.'},
 {'domain': 'Science',
  'question': 'Magnet activity: best next step after noticing some objects stick?',
  'options': ['Test and sort more objects', 'Stop and give the answer', 'Remove materials', 'Turn it into spelling'],
  'answer': 0,
  'explanation': 'Further testing extends inquiry.'},
 {'domain': 'Physical Development',
  'question': 'Which activity most directly supports gross-motor development?',
  'options': ['Running, jumping, and balancing', 'Turning book pages', 'Stringing beads', 'Drawing small circles'],
  'answer': 0,
  'explanation': 'Large-muscle movement builds gross-motor skill.'},
 {'domain': 'Physical Development',
  'question': 'Which activity most directly supports fine-motor development?',
  'options': ['Using tongs to move small objects', 'Running a relay', 'Jumping', 'Climbing stairs'],
  'answer': 0,
  'explanation': 'Tongs build hand and finger control.'},
 {'domain': 'Physical Development',
  'question': 'A child is learning to use scissors. Best support?',
  'options': ['Provide child-safe scissors, model, and supervise', 'Give sharp adult scissors', 'Do all cutting', 'Forbid practice'],
  'answer': 0,
  'explanation': 'Safe guided practice supports skill and independence.'},
 {'domain': 'Physical Development',
  'question': 'Which practice supports children with varied physical abilities?',
  'options': ['Offer adapted materials and multiple ways to participate',
              'Use one activity with no modifications',
              'Exclude children who move differently',
              'Compare publicly'],
  'answer': 0,
  'explanation': 'Inclusive adaptations support participation.'},
 {'domain': 'Physical Development',
  'question': 'Balance beams, hopping games, and obstacle paths mainly support:',
  'options': ['Balance and coordination', 'Narrative comprehension', 'Number symbols', 'Vocabulary only'],
  'answer': 0,
  'explanation': 'These activities build body control and coordination.'},
 {'domain': 'Health',
  'question': 'Best way to reduce spread of many classroom germs?',
  'options': ['Teach and model effective handwashing', 'Share cups', 'Skip cleaning', 'Use one towel for everyone'],
  'answer': 0,
  'explanation': 'Consistent hygiene routines reduce transmission.'},
 {'domain': 'Health',
  'question': 'Which practice best supports healthy eating habits?',
  'options': ['Offer varied nutritious foods without forcing', 'Require a clean plate', 'Use food as punishment', 'Shame preferences'],
  'answer': 0,
  'explanation': 'Responsive feeding supports healthy attitudes.'},
 {'domain': 'Health',
  'question': 'A child coughs into their hands before touching shared materials. Best response?',
  'options': ['Remind about cough hygiene and handwashing', 'Embarrass the child', 'Ignore it', 'Remove the child permanently'],
  'answer': 0,
  'explanation': 'Calm reminders teach health routines.'},
 {'domain': 'Health',
  'question': 'Why are consistent toileting and handwashing routines useful?',
  'options': ['They support health, independence, and predictable self-care',
              'They replace supervision',
              'They are only for older children',
              'They eliminate all need for help'],
  'answer': 0,
  'explanation': 'Predictable routines build health habits and self-help.'},
 {'domain': 'Health',
  'question': 'Possible health concern: best general response?',
  'options': ['Follow site procedures and notify appropriate staff',
              'Diagnose the child yourself',
              'Give medication without authorization',
              'Post it publicly'],
  'answer': 0,
  'explanation': 'Health concerns should follow established procedures.'},
 {'domain': 'History–Social Science',
  'question': 'A classroom job chart mainly helps children learn about:',
  'options': ['Roles and responsibility in a community', 'Phoneme segmentation', 'Measurement', 'Gross motor control'],
  'answer': 0,
  'explanation': 'Classroom jobs build understanding of community roles.'},
 {'domain': 'History–Social Science',
  'question': 'Which activity supports understanding of past and present?',
  'options': ['Comparing baby photos with current photos', 'Sorting shapes', 'Clapping syllables', 'Jumping patterns'],
  'answer': 0,
  'explanation': 'Comparing earlier and current experiences builds time concepts.'},
 {'domain': 'History–Social Science',
  'question': "Books reflecting children's families and communities support:",
  'options': ['Identity and understanding of diverse communities', 'Only number sense', 'Only physical strength', 'Only print direction'],
  'answer': 0,
  'explanation': 'Representation connects learning to family and community.'},
 {'domain': 'History–Social Science',
  'question': 'Which activity introduces simple geography?',
  'options': ['Using a classroom map to locate familiar areas', 'Memorizing state capitals', 'Completing algebra', 'Copying paragraphs'],
  'answer': 0,
  'explanation': 'Maps of familiar spaces build spatial understanding.'},
 {'domain': 'History–Social Science',
  'question': 'Children vote between two class songs. This introduces:',
  'options': ['Group decision-making', 'Phonological awareness', 'Fine-motor control', 'Scientific measurement'],
  'answer': 0,
  'explanation': 'Voting introduces shared decision-making.'},
 {'domain': 'Visual & Performing Arts',
  'question': 'In open-ended art, the adult should generally:',
  'options': ['Emphasize exploration and process', 'Require identical products', 'Correct every color choice', 'Finish the work'],
  'answer': 0,
  'explanation': 'Open-ended art supports creativity and expression.'},
 {'domain': 'Visual & Performing Arts',
  'question': 'Which activity best supports dramatic play?',
  'options': ['Props for a pretend grocery store', 'Copying a worksheet', 'Timed counting', 'Silent sitting'],
  'answer': 0,
  'explanation': 'Props and role play support imagination and language.'},
 {'domain': 'Visual & Performing Arts',
  'question': 'Children move scarves to music. This integrates:',
  'options': ['Music, movement, and creative expression', 'Only mathematics', 'Only writing', 'Only health'],
  'answer': 0,
  'explanation': 'Movement to music supports creative expression.'},
 {'domain': 'Visual & Performing Arts',
  'question': 'When a child explains a painting, best response?',
  'options': ['Listen and invite the child to describe ideas',
              'Tell the child what it must mean',
              'Correct imagination',
              "Compare it with another child's work"],
  'answer': 0,
  'explanation': 'Inviting explanation supports expression and language.'},
 {'domain': 'Visual & Performing Arts',
  'question': 'Which material best encourages creative construction?',
  'options': ['Blocks, fabric, boxes, and loose parts', 'Only worksheets', 'Only multiple-choice cards', 'Only pencils'],
  'answer': 0,
  'explanation': 'Open-ended materials support design and creativity.'},
 {'domain': 'Professional Practice & Inclusion',
  'question': 'Which observation note is most objective?',
  'options': ['Mia left the carpet three times during the 10-minute activity.',
              'Mia was badly behaved.',
              'Mia did not care about learning.',
              'Mia wanted to cause trouble.'],
  'answer': 0,
  'explanation': 'Objective notes describe observable actions, not motives.'},
 {'domain': 'Professional Practice & Inclusion',
  'question': 'A child with a disability participates in a group. Best support?',
  'options': ['Provide needed access while encouraging participation and independence',
              'Automatically exclude the child',
              'Do everything for the child',
              'Lower all expectations'],
  'answer': 0,
  'explanation': 'Inclusive support balances access and independence.'},
 {'domain': 'Professional Practice & Inclusion',
  'question': 'When giving assistance, best general principle?',
  'options': ['Provide the least help needed for successful participation',
              'Always do the task',
              'Never help',
              'Use identical help for every child'],
  'answer': 0,
  'explanation': 'Appropriate scaffolding supports competence.'},
 {'domain': 'Professional Practice & Inclusion',
  'question': 'Which interaction is culturally responsive?',
  'options': ['Learn about families and use respectful representation',
              'Assume all families are the same',
              'Avoid family languages',
              'Use stereotypes'],
  'answer': 0,
  'explanation': 'Responsive practice values family, language, and community.'},
 {'domain': 'Professional Practice & Inclusion',
  'question': "A parent asks about another child's behavior. Best response?",
  'options': ["Protect the other child's privacy", 'Share details', 'Show records', 'Ask children to explain'],
  'answer': 0,
  'explanation': 'Professional practice includes confidentiality.'},
 {'domain': 'Professional Practice & Inclusion',
  'question': 'A child struggles with a routine. Before assuming defiance, the adult should:',
  'options': ['Observe possible causes and provide support', 'Use a negative label', 'Punish immediately', 'Compare to peers'],
  'answer': 0,
  'explanation': 'Observation is more useful than assumptions.'},
 {'domain': 'California ECE Scenario Challenge',
  'question': 'A child keeps grabbing materials from peers. Best first teaching response?',
  'options': ['Move close, state the expectation calmly, and coach requesting or waiting',
              'Yell across the room',
              'Label the child selfish',
              'Remove the child all day'],
  'answer': 0,
  'explanation': 'Calm coaching teaches a replacement social skill.'},
 {'domain': 'California ECE Scenario Challenge',
  'question': 'A child learning English watches but does not speak during a song. Best response?',
  'options': ['Allow observation, model gestures, and invite participation without pressure',
              'Require a solo',
              'Assume no understanding',
              'Exclude the child'],
  'answer': 0,
  'explanation': 'Low-pressure entry and visual support encourage participation.'},
 {'domain': 'California ECE Scenario Challenge',
  'question': 'Two children disagree about which object will float. Best response?',
  'options': ['Invite both predictions and test the object',
              "Choose the older child's answer",
              'Tell them disagreement is bad',
              'End the activity'],
  'answer': 0,
  'explanation': 'Testing predictions turns disagreement into inquiry.'},
 {'domain': 'California ECE Scenario Challenge',
  'question': 'A child can zip most of a coat but struggles with the first step. Best support?',
  'options': ['Help with the first step, then let the child continue',
              'Zip the whole coat every time',
              'Tell the child to stop trying',
              'Ask another child to do it'],
  'answer': 0,
  'explanation': 'Partial assistance preserves independence.'},
 {'domain': 'California ECE Scenario Challenge',
  'question': 'While documenting an incident, which note is best?',
  'options': ["At 10:15, Leo pushed the red truck away and said, 'My turn,' while Ava held it.",
              'Leo was aggressive again.',
              'Leo was trying to be mean.',
              'Leo never behaves.'],
  'answer': 0,
  'explanation': 'Objective documentation records observable actions and words.'}]
DOMAINS=sorted(set(q["domain"] for q in QUESTIONS))
STUDY={
"Approaches to Learning":["Support initiative, persistence, attention, flexible problem-solving, self-regulation, and collaboration.","Use accessible materials and meaningful choices.","Give process-focused feedback about effort and strategy."],
"Social & Emotional Development":["Support emotional awareness, self-regulation, empathy, peer interaction, cooperation, and relationships.","Coach social problems rather than shame children."],
"Language, Literacy & English Language Development":["Use conversation, read-alouds, songs, sound play, meaningful print, emergent writing, and retelling.","Support multilingual learners with visuals, gestures, routines, conversation, and respect for home language."],
"Mathematics":["Use concrete experiences with counting, quantity, classification, patterns, shapes, measurement, and reasoning.","Ask children to explain how they know."],
"Science":["Encourage observation, prediction, testing, comparison, questioning, and discussion of evidence.","Use real materials and open-ended investigations."],
"Physical Development":["Provide safe opportunities for large- and small-muscle development, balance, coordination, and adapted participation.","Support increasing independence."],
"Health":["Teach healthy routines such as handwashing, cough hygiene, self-care, and safe eating practices.","Follow program procedures for health concerns."],
"History–Social Science":["Explore family, community, roles, responsibility, time, place, maps, and group decision-making.","Represent diverse families and communities respectfully."],
"Visual & Performing Arts":["Use open-ended art, dramatic play, music, movement, and creative materials.","Emphasize exploration and expression over identical products."],
"Professional Practice & Inclusion":["Document objectively; describe what you see and hear, not motives.","Use inclusion, scaffolding, confidentiality, culturally responsive practice, and strength-based feedback."]
}
for key,val in {"qs":[],"i":0,"score":0,"answered":False,"selected":None,"wrong":[]}.items():
    if key not in st.session_state: st.session_state[key]=val
def start(pool,n):
    n=min(n,len(pool)); st.session_state.qs=random.sample(pool,n)
    st.session_state.i=0; st.session_state.score=0; st.session_state.answered=False
    st.session_state.selected=None; st.session_state.wrong=[]
st.title("🌴 California ECE Practice")
st.caption("New California-focused practice app. Original questions aligned to current PTKLF themes; not an official state, district, or testing-vendor exam.")
home,study,practice,scenario,review=st.tabs(["🏠 Home","📚 California Study","📝 Practice Tests","🎯 Scenario Challenge","✅ Final Review"])
with home:
    st.header("California-focused ECE preparation")
    st.write("This version replaces the earlier app based on your uploaded study sheets.")
    st.info("Recommended: California Study → 50-question mixed test → Scenario Challenge → review mistakes.")
    for d in DOMAINS: st.write("• "+d)
with study:
    st.header("📚 California ECE Study Guide")
    for title,bullets in STUDY.items():
        with st.expander(title):
            for b in bullets: st.write("• "+b)
with practice:
    st.header("📝 Practice Tests")
    c1,c2,c3=st.columns(3)
    if c1.button("20-Question Warm-Up",type="primary"): start(QUESTIONS,20); st.rerun()
    if c2.button("50-Question Mixed Test"): start(QUESTIONS,50); st.rerun()
    if c3.button("Full Question Bank"): start(QUESTIONS,len(QUESTIONS)); st.rerun()
    domain=st.selectbox("Or practice one area",DOMAINS)
    if st.button("Start Topic Practice"):
        pool=[q for q in QUESTIONS if q["domain"]==domain]; start(pool,len(pool)); st.rerun()
    if st.session_state.qs:
        qs=st.session_state.qs; i=st.session_state.i
        if i<len(qs):
            q=qs[i]; st.progress(i/len(qs)); st.write(f"**Question {i+1} of {len(qs)} • {q['domain']}**")
            st.subheader(q["question"])
            opts=q["options"][:]; random.Random(i+777).shuffle(opts)
            sel=st.radio("Choose the best answer:",opts,index=None,key=f"ans_{i}")
            if not st.session_state.answered:
                if st.button("Submit Answer",type="primary"):
                    if sel is None: st.warning("Select an answer first.")
                    else:
                        st.session_state.selected=sel; st.session_state.answered=True
                        if sel==q["options"][q["answer"]]: st.session_state.score+=1
                        else: st.session_state.wrong.append(q)
                        st.rerun()
            else:
                correct=q["options"][q["answer"]]
                if st.session_state.selected==correct: st.success("✅ Correct")
                else: st.error("❌ Review this one"); st.write("**Best answer:** "+correct)
                st.info(q["explanation"])
                if st.button("Next Question",type="primary"):
                    st.session_state.i+=1; st.session_state.answered=False; st.session_state.selected=None; st.rerun()
        else:
            total=len(qs); pct=round(st.session_state.score/total*100)
            st.success(f"Score: {st.session_state.score}/{total} ({pct}%)")
            if pct>=90: st.balloons(); st.success("Excellent.")
            elif pct>=80: st.success("Strong. Review missed concepts.")
            else: st.warning("Review missed concepts, then try another set.")
            if st.session_state.wrong:
                st.subheader("Missed questions")
                for q in st.session_state.wrong: st.write("• "+q["question"])
with scenario:
    st.header("🎯 California ECE Scenario Challenge")
    for q in [x for x in QUESTIONS if x["domain"]=="California ECE Scenario Challenge"]:
        with st.expander(q["question"]):
            st.write("**Best answer:** "+q["options"][q["answer"]]); st.write(q["explanation"])
with review:
    st.header("✅ Final Review")
    st.markdown("""
- Choose **developmentally appropriate, respectful, and inclusive** responses.
- Prefer **teaching and scaffolding** over punishment or taking over.
- Use **objective observation**, not labels or assumptions.
- Encourage **independence** while giving needed support.
- Treat **home language, family, culture, and abilities as assets**.
- Favor **play, conversation, inquiry, real materials, and active participation**.
- On hard questions, choose the answer that best supports **learning, dignity, participation, and development**.
""")
    st.success("Read carefully and choose the BEST answer.")
st.divider()
st.caption("Independent study aid based on current California ECE/PTKLF themes. Not affiliated with CDE, IUSD, or a testing vendor.")
